#!/bin/bash

SCRIPTPATH=$(readlink -f "$0") 
APPROOT=$(dirname "$SCRIPTPATH") 
JARFILE="$APPROOT/SyncanyCore.jar"
	
if [ ! -e "$JARFILE" ]; then
	echo "Cannot find jar file in app root $APPROOT"
	exit 1
fi

java -Xmx1024m -Dfile.encoding="UTF-8" -jar "$JARFILE" $@
