#!/bin/sh

ln -s /usr/share/syncany/bin/syncany /usr/bin/syncany
ln -s /usr/share/syncany/bin/sy /usr/bin/sy
ln -s /usr/share/syncany/bin/syncanyd /usr/bin/syncanyd
ln -s /usr/share/syncany/bin/syd /usr/bin/syd

#DEBHELPER#
exit 0
